version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Sử dụng environment variables cho production
      - SPRING_DATASOURCE_URL=${DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=${PORT:-8080}
    restart: unless-stopped
